joint_limits:
  ur10_arm_wrist_2_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_palm_finger_1_joint:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  ur10_arm_wrist_1_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_middle_joint_2:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  ur10_arm_shoulder_lift_joint:
    has_velocity_limits: true
    max_velocity: 2.16
    has_acceleration_limits: false
    max_acceleration: 0
  ur10_arm_shoulder_pan_joint:
    has_velocity_limits: true
    max_velocity: 2.16
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_2_joint_1:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_1_joint_3:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_palm_finger_2_joint:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_middle_joint_3:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_middle_joint_1:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  ur10_arm_wrist_3_joint:
    has_velocity_limits: true
    max_velocity: 3.2
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_2_joint_3:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  ur10_arm_elbow_joint:
    has_velocity_limits: true
    max_velocity: 3.15
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_1_joint_1:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_2_joint_2:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  robotiq_finger_1_joint_2:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0