controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: true
    type: FollowJointTrajectory
    joints: [ur10_arm_shoulder_pan_joint, ur10_arm_shoulder_lift_joint, ur10_arm_elbow_joint, ur10_arm_wrist_1_joint, ur10_arm_wrist_2_joint, ur10_arm_wrist_3_joint, ee_joint]
